app.name=Data Experiment:
app.frame.width=500
app.frame.height=500
app.plot.insets.top=10
app.plot.insets.left=50
app.plot.insets.right=10
app.plot.insets.bottom=40

app.plot.type=XY
app.plot.tick=yes


