app.name=Data and Plot
app.version=1.0.0
app.data.size=100
app.data.stepMultiplicator=1.0
app.data.type=SINE_LINE_NOISE

app.data.sine.amplitude=5.0
app.data.sine.thetaInit=0
app.data.sine.thetaStep=15

app.data.line.a=1.0
app.data.line.b=0

app.data.noise.noiseLevel=3.0
