app.data.title=Data and Plot
app.data.size=10
app.data.stepMultiplicator=1.0

app.data.1.name=Sine Data
app.data.1.funType=SINE
app.data.1.sine.amplitude=1.0
app.data.1.sine.thetaInit=0
app.data.1.sine.thetaStep=15